### ISSUE TITLE
Sample app?

### ISSUE THREAD

**Issue by selangley-wa** [jtcrowson/NgRx-MockStore#1]
Do you have a sample app that makes use of Angular 6 and NGRX 6?

Because when I try using NgRX-Mock store in one of the spec files of my app I get the error:

```
	Failed: Unexpected value 'ActionsSubject' imported by the module 'DynamicTestModule'. Please add a @NgModule annotation.
	error properties: Object({ ngSyntaxError: true })
	Error: Unexpected value 'ActionsSubject' imported by the module 'DynamicTestModule'. Please add a @NgModule annotation.
	    at syntaxError (http://localhost:9876/node_modules/@angular/compiler/fesm5/compiler.js?:1021:1)
	    at http://localhost:9876/node_modules/@angular/compiler/fesm5/compiler.js?:10583:1
	    at <Jasmine>
```

Thanks!

**Comment by jtcrowson** [comment]
Hey @selangley-wa, let me add one.  Is the project available on public GitHub?  I can take a look.

**Comment by selangley-wa** [comment]
Sorry, it's not on GitHub.  The lawyers likely wouldn't allow me to upload it, but I could give you some feedback if you have questions.

**Comment by jtcrowson** [comment]
I added an example Angular/NgRx v6 project.  Used ngrx-mockstore in the `add.component.spec.ts`.  Let me know if that helps uncover the issue.

https://github.com/jtcrowson/ngrx-mockstore-example

**Comment by jtcrowson** [comment]
@selangley-wa any luck here?

**Comment by selangley-wa** [comment]
Thanks for the example.  It made me realize I was using provideMockStore() incorrectly by putting it in the imports section rather than the providers section where it belongs. That appears to be the source of the difficulties I was encountering. All good now.
